### ISSUE TITLE
Landing page v0 brainstorm and mocks

### ISSUE THREAD

**Issue by benigeri** [reactiflux/reactiflux.com#1]
_I'll update the answers to these questions based on our discussion below. Answers can change if we come up better ones._
### 3. What should the landing page look like?

Let's wait until 1 + 2 are answered, then we can start putting mocks together.

**Comment by benigeri** [comment]
My take: 

### 1. What do we include on the new landing page?

For the very first version, we can get away with: 
 - logo / description
 - invitation form with user count (online/total), just like Slackin
 - a list of featured channels (manually configured to start)

Eventually, we can add things like channel statistics from the Slack API, and add some nice graphs, but let's start with something simple. 

### 2. Do we want to use Slackin?

My guess is not. It doesn't seem like the input form would be easy to include into our landing page. I may be mistaken. We should probably grab the code it uses to make the API call, and any other useful stuff, but I don't think it makes sense to use all their code.

**Comment by pburtchaell** [comment]
Hey there, I saw this in a tweet and think it would be great to see a Reactifpux homepage (or website in general if there is too much for one page), so I figured I'd jump in on the conversation. 

My thoughts:
1. Logo, description, invite form, list of featured channels, list of moderators (a list might not be the best format depending on how many mods there are/how you handle mods)
2. I think building something similar to Slackin would be great, but it would be nice to have something more custom (and written in React + Flux of course :smile:).

Also, I think it would be good to include a code of conduct (and possibly instructions on how to report users?) somewhere on a separate page.

**Comment by benigeri** [comment]
Good idea to bring up moderators / code of conduct. None of that exists yet, so we'll have to figure out what to include there. 

> 2. I think building something similar to Slackin would be great, but it would be nice to have something more custom (and written in React + Flux of course :smile:).
:+1:

**Comment by pburtchaell** [comment]
Do you have any ideas on where to start with the code of conduct?

PS: I am happy to help with either design or dev of the homepage (or both—where ever I could help, really!). Just let me know if you need it.

**Comment by benigeri** [comment]
> Do you have any ideas on where to start with the code of conduct or how you want to approach that?

I'll create a repo for it. IMO we should keep it simple and straight forward. We haven't really needed anything so farm. Maybe just two points: 1. no spam  2. no abuse

> PS: I am happy to help with either design or dev of the homepage (or both—where ever I could help, really!). Just let me know if you need it.

Would be amazing to get your help on either. I added your here, hopefulll that's ok with you: https://github.com/reactiflux/volunteers 

If you want to start designing it, go for it. Are you comfortable using Sketch?

**Comment by pburtchaell** [comment]
> If you want to start designing it, go for it. Are you comfortable using Sketch?

Surely. I can try to put something together for the weekend.

**Comment by sotojuan** [comment]
I'd be down to work on the landing page, but you probably don't want me designing anything. Let me know when there's a game plan/coding to be done and I'll help out!

**Comment by vcarl** [comment]
For the time being, I'll update what's already there and push it live tonight.

**Comment by jbhatab** [comment]
Here's the template Scott made for Reactiflux. I'm sure we can port over the slack based visuals to discord pretty easily.

![landing_5](https://cloud.githubusercontent.com/assets/2458718/10566574/aa36114c-75b0-11e5-87df-55bf3ee0e8eb.png)
