### ISSUE TITLE
reactiflux.com does not update job proposals list

### ISSUE THREAD

**Issue by aeworxet** [reactiflux/reactiflux.com#167]
Last job proposal at [https://www.reactiflux.com/jobs](https://www.reactiflux.com/jobs) is dated 'September 23rd 2020' while there were already a lot of proposals after that time, according to **#job-board** channel.

`https://reactistory.com:8443/api/job?type=hiring&range=180&limit=50&after=758124439879024681` (specified in current JSON) replies with an empty JSON:
```
{
  "messages": [],
  "paginate": {}
}
```
So I assume something's wrong at `reactistory.com`'s side.

**Comment by nickserv** [comment]
It seems like the Discord integration has been broken since we started requiring users to accept the Code of Conduct (which also applies to bot accounts). We'll look into this, thanks.

**Comment by nickserv** [comment]
We have fixed the bot account so new postings should be shown as of today.

**Comment by aeworxet** [comment]
Same issue (last job advertisement at [https://www.reactiflux.com/jobs](https://www.reactiflux.com/jobs) is dated 'January 31st 2021'), probably same actions need to be taken to resolve it.

**Comment by BTMPL** [comment]
Thanks for the heads up @aeworxet - I'll take a look.
