### ISSUE TITLE
Make dates visible on transcripts

### ISSUE THREAD

**Issue by gabegreenberg** [reactiflux/reactiflux.com#17]
Dates are available on transcripts but they aren't visible as they were added just to order the transcripts. Let's change that.

**Comment by gabegreenberg** [comment]
@Huvik do you have some time to do this? I'm afk the rest of the night :)

**Comment by huv1k** [comment]
I will do it tomorrow

**Comment by gabegreenberg** [comment]
@Huvik thanks that would be awesome :)

**Comment by TryingToImprove** [comment]
I can also do it, if @Huvik don't have time.. :-)

**Comment by gabegreenberg** [comment]
@TryingToImprove sure that would be great Oliver!! Thanks

**Comment by huv1k** [comment]
you can do it if you want, i am going to do it today so if you want contribute just say :)

**Comment by TryingToImprove** [comment]
@Huvik I would like to contribute.. I have created a pull request, but I was not sure how it should look.. :)
