### ISSUE TITLE
Horizontal scrollbar appears for a small range of browser widths

### ISSUE THREAD

**Issue by jsonnull** [reactiflux/reactiflux.com#18]
I noticed a small range of browser widths for which there's a horizontal scrollbar.

It looks like breakpoint at which the logotype is made smaller should be changed. 

I'm seeing the scrollbar starting at the 1020px breakpoint when the logotype becomes larger, and it remains until about 1053px wide.

**Comment by huv1k** [comment]
Can you send screenshot or something? I was trying to reproduce it but no luck.

**Comment by huv1k** [comment]
@jsonnull ? :)

**Comment by jsonnull** [comment]
Heya @Huvik sorry for the epic delay.

I'm unable to recreate it for the original 1020px breakpoint but I'm seeing it at a smaller one now.

<img width="444" alt="screen shot 2017-02-23 at 7 30 34 pm" src="https://cloud.githubusercontent.com/assets/5249539/23285354/b038df56-f9fe-11e6-8326-5234d11a110b.png">

**Comment by Huvik** [comment]
Yea, it happens in current version of firefox, but in developer version is ok and its small glitch and its because of flex space-between. I don't know why :D strange

**Comment by huv1k** [comment]
Fixed
