### ISSUE TITLE
Q&A transcript links scroll to top before navigating

### ISSUE THREAD

**Issue by vcarl** [reactiflux/reactiflux.com#181]
I noticed you need to click quickly on a name in the navigation in order to successfully load a different transcript, long clicks incorrectly scroll to the top before navigation begins

https://user-images.githubusercontent.com/1551487/103490121-abcc2900-4de7-11eb-88d0-652fdedec223.mov

**Comment by willypraditya** [comment]
Also happens in Learning and Tips sidebar.

**Comment by nickserv** [comment]
I don't think this is an issue anymore, since we only show one transcript at a time, and navigation works on the Learning page.
