### ISSUE TITLE
[Feature request] HTML Anchor for each question in transcripts

### ISSUE THREAD

**Issue by ncuillery** [reactiflux/reactiflux.com#20]
It could be great to have an anchor on each question in transcripts in order to have a shareable link to a particular question.

Something like: 
https://www.reactiflux.com/transcripts/mike-grabowski/#what-are-your-thoughts-on-angular-2

A simple integer sequence could do the trick too:
https://www.reactiflux.com/transcripts/mike-grabowski/#4

**Comment by huv1k** [comment]
It's not doable in current state, because there are different layout of q&a. We have to change it to same layout to do it.

**Comment by BTMPL** [comment]
#29 is done I believe, so I will try to get this one done this weekend. 

We had a short talk with Huvik and I think we can make a regex to add anchors before `**Q:**` now

**Comment by huv1k** [comment]
Or we can wait little bit until Gatsby 1.0 is out and test new cool stuff :) How @KyleAMathews said on discord channel :)
