### ISSUE TITLE
bug: wrong tab title on Q&A schedule page

### ISSUE THREAD

**Issue by Miqhtiedev** [reactiflux/reactiflux.com#214]
Upon going to the [Q&A schedule page](https://www.reactiflux.com/schedule) the title of the tab at the top shows *Transcripts* instead of something like *Schedule*
![](https://i.imgur.com/EvvE9MI.png)

**Comment by ANSH4195** [comment]
I can solve this right away, should I?

**Comment by ANSH4195** [comment]
#216
I have corrected it, please take a look.
