### ISSUE TITLE
Issue in Navbar responsiveness in mobile view. 

### ISSUE THREAD

**Issue by rohanpadhye-cmd** [reactiflux/reactiflux.com#231]
While surfing the website, I encountered a navigation bar styling problem (in mobile view).
I'd like to resolve this issue & contribute a few to this project. 
So I appeal assign me to this one 👍🏻

**Comment by vcarl** [comment]
Go for it!

**Comment by rohanpadhye-cmd** [comment]
> Go for it!

On it !!🔥

**Comment by vcarl** [comment]
Whoops, closed in #232. Ty again!
