### ISSUE TITLE
Q&A transcripts should have a more consistent format

### ISSUE THREAD

**Issue by vcarl** [reactiflux/reactiflux.com#29]
We have like 6 different formats for Q&A transcripts. It would be helpful for styling and other functionality (like #20) if they were more consistent.

@gabegreenberg and I have previously talked about it, and think the format of Cheng Lou and Jordan Walke's sessions is what we'd like to use going forward. We need to edit the past transcripts to meet that style and trim any non-question/answer chatter.

- [x] Andrew Clark
- [x] Ben Alpert
- [x] Cheng Lou
- [x] Christopher Chedeau
- [x] Dan Abramov
- [x] Devin Abbott
- [x] Eric Vicenti
- [x] Jonathan Carter & Geoffrey Goh
- [x] Jordan Walke
- [x] Lee Byron
- [x] Mike Grabowski
- [x] Relay Team
- [x] Ryan Florence

**Comment by BTMPL** [comment]
I'll look into it.

**Comment by gabegreenberg** [comment]
@vcarl @BTMPL yes that would be awesome and much needed.

**Comment by BTMPL** [comment]
FYI - I'm working on this in my fork at https://github.com/BTMPL/reactiflux.com

**Comment by gabegreenberg** [comment]
@BTMPL awesome thanks!!

**Comment by TryingToImprove** [comment]
Is it done with #35 ?

**Comment by BTMPL** [comment]
Hello @TryingToImprove we are still missing 2 transcripts to be changed in to the propper format, and then this one will be implemented; I'm working on one of the 2 transcripts so ETA this week :crossed_fingers:

**Comment by BTMPL** [comment]
Think we can close this one now.

**Comment by huv1k** [comment]
Great job!
