### ISSUE TITLE
issue while authenticate using discord

### ISSUE THREAD

**Issue by dipak-tomar** [reactiflux/reactiflux.com#312]
<img width="1439" alt="Screenshot 2024-07-04 at 10 05 10 AM" src="https://github.com/reactiflux/reactiflux.com/assets/88227322/dfa1eae6-8a98-4cde-9413-f832a43150d2">

some issue while using discord for signing into reactiflux job board

**Comment by dipak-tomar** [comment]
still not working as i dont have anywhere written not verified email

**Comment by vcarl** [comment]
I'm not sure what you mean by that. I'm not sure what to tell you, I'm not able to produce a Discord account that replicates the behavior you're seeing

**Comment by vcarl** [comment]
I've finally gotten some time free to dig deeper, this looks like it was probably a combination of bad error handling + rate limit on a poor choice of endpoint #320
