### ISSUE TITLE
*Eric Elliott's Essential Javascript Links* 404 link

### ISSUE THREAD

**Issue by odv** [reactiflux/reactiflux.com#48]
Hi!

*Eric Elliott's Essential Javascript Links* now results to a 404 link because the author of this repository has deleted it. 
I've submitted PR #47 in order to fix this issue.

**Comment by odv** [comment]
PR #47 has been merged so I'm closing this issue. Thank you!

**Comment by vcarl** [comment]
Thanks @odv!
