### ISSUE TITLE
jobs.reactiflux.com fetch failed and certificate not secure

### ISSUE THREAD

**Issue by damaera** [reactiflux/reactiflux.com#72]
im trying to search jobs in jobs.reactiflux.com
but always searching....
and connection not secure
![image](https://user-images.githubusercontent.com/5365957/46245935-a3266480-c420-11e8-85bf-4ae36e74cf5b.png)

**Comment by BTMPL** [comment]
Probably the letsencrypt certificate expired. I'll look into it asap, thank you for reporting.

**Comment by damaera** [comment]
you're welcome

**Comment by BTMPL** [comment]
Should be OK now - the cert did auto renew but the express server does not automatically restart so didn't start serving the new one.
